---
- hosts: "{{ host }}"

  vars:
    # renovate: datasource=github-releases depName=lazygit packageName=jesseduffield/lazygit
    version: v0.58.0

  tasks:
    - name: Create local bin path
      ansible.builtin.file:
        path: ~/.local/bin
        state: directory

    - name: Check if lazygit is installed
      shell: "lazygit --version | grep {{ version[1:] }}"
      changed_when: false
      failed_when: lazygit_installed.rc not in [0,1]
      register: lazygit_installed

    - name: Install lazygit
      when: lazygit_installed.rc not in [ 0 ]
      unarchive:
        remote_src: yes
        src: "https://github.com/jesseduffield/lazygit/releases/download/{{ version }}/lazygit_{{ version[1:] }}_Linux_x86_64.tar.gz"
        dest: ~/.local/bin
        extra_opts:
          - lazygit
