---
- hosts: "{{ host }}"

  # https://github.com/JaKooLit/Debian-Hyprland/blob/main/install-scripts/aquamarine.sh

  vars:
    # renovate: datasource=github-tags depName=aquamarine packageName=hyprwm/aquamarine
    version: v0.10.0
    dir: "/tmp/hyprwm-aquamarine"

  tasks:
    - name: Check if skip
      meta: end_play
      when: '"hyprland" in skip'

    - name: Checkout aquamarine
      ansible.builtin.git:
        repo: https://github.com/hyprwm/aquamarine.git
        dest: "{{ dir }}"
        recursive: true
        version: "{{ version }}"
        force: true

    - name: Build aquamarine
      shell:
        chdir: "{{ dir }}"
        cmd: |
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
          cmake --build ./build --config Release --target all -j `nproc`

    - name: Install aquamarine
      become: true
      shell:
        chdir: "{{ dir }}"
        cmd: |
          sudo cmake --install ./build
