---
- hosts: "{{ host }}"

  # https://github.com/JaKooLit/Debian-hyprpaper/blob/main/install-scripts/hyprpaper.sh

  vars:
    # renovate: datasource=github-tags depName=hyprpaper packageName=hyprwm/hyprpaper
    version: v0.8.3
    dir: "/tmp/hyprwm-hyprpaper"

  tasks:
    - name: Check if skip
      meta: end_play
      when: '"hyprland" in skip'

    - name: Checkout hyprpaper
      ansible.builtin.git:
        repo: https://github.com/hyprwm/hyprpaper.git
        dest: "{{ dir }}"
        recursive: true
        version: "{{ version }}"
        force: true

    - name: Build hyprpaper
      shell:
        chdir: "{{ dir }}"
        cmd: |
          cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
          cmake --build ./build --config Release --target hyprpaper -j `nproc 2`

    - name: Install hyprpaper
      become: true
      shell:
        chdir: "{{ dir }}"
        cmd: |
          sudo cmake --install ./build
